app_author/urls.py
from django.urls import path

from . import views

app_name = 'app_author'
urlpatterns = [
    path('<slug:slug>/edit', views.author_edit_view, name='author_edit'),
    path('<slug:slug>', views.author_single_view, name='author_single'),
]

app_forum/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'app_forum'
urlpatterns = [
    path('', views.forum_list_view, name='forum_list'),
    path('thread/new/', views.forum_new_view, name='forum_new'),
    path('thread/<int:pk>/', views.forum_single_view, name='forum_single'),
    path('thread/<int:pk>/edit/', views.forum_edit_view, name='forum_edit'),
    path(
        'thread/<int:pk>/comment/edit/<int:id>/',
        views.forum_comment_edit_view,
        name='forum_comment_edit',
    ),
]

admin.site.site_header = 'Django-ID Dashboard'

djangoid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from markdownx import urls as markdownx

urlpatterns = [
    # Main App
    path('', include('app_forum.urls', namespace='forum')),
    path('author/', include('app_author.urls', namespace='author')),
    path('admin/', admin.site.urls),

    # 3rd-party App
    path('markdownx/', include(markdownx)),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_author/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


# CUSTOM FILE SIZE VALIDATOR


def validate_image(fieldfile_obj):
    """
    Limit image size upload
    """
    filesize = fieldfile_obj.file.size
    megabyte_limit = 0.5
    if filesize > megabyte_limit*1024*1024:
        raise ValidationError("Max file size is %sMB" % str(megabyte_limit))


class Profile(models.Model):
    """
    Author Model
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )

    profile_picture = models.ImageField(
        upload_to='images/%Y/%m/%d',
        validators=[validate_image],
        blank=True,
        null=True
    )

    profile_name = models.CharField(
        verbose_name='Name',
        null=True,
        blank=True,
        max_length=50
    )

    profile_email = models.EmailField(
        verbose_name='Email Address',
        null=True,
        blank=True
    )

    profile_location = models.CharField(
        verbose_name='Origin/City',
        null=True,
        blank=True,
        max_length=50
    )

    profile_github = models.URLField(
        verbose_name='Github URL',
        null=True,
        blank=True
    )

    slug = models.SlugField()

    is_created = models.DateTimeField(
        null=True,
        blank=True
    )

    is_moderator = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return str(self.user)

    def save(self, **kwargs):
        if not self.slug:
            from djangoid.utils import get_unique_slug
            self.slug = get_unique_slug(instance=self, field='profile_name')
        super(Profile, self).save(**kwargs)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """
    Automatically Create User when Login
    """
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """
    Automatically Create User when Login
    """
    instance.profile.save()

app_author/forms.py
from django import forms

from .models import Profile


class ProfileForm(forms.ModelForm):
    """
    Author Form
    """
    class Meta:
        model = Profile
        fields = [
            'profile_picture',
            'profile_name',
            'profile_email',
            'profile_location',
            'profile_github'
        ]
        exclude = ['user']
        widgets = {'user': forms.HiddenInput()}

app_author/views.py
from .forms import ProfileForm
from .models import Profile
from django.db.models import Count
from app_forum.models import Forum, Comment
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404


def author_single_view(request, slug):
    """
    Render Single User
    :param request:
    :param slug:
    :return:
    """
    author = get_object_or_404(Profile, slug=slug)
    author_forum_list = Forum.objects.filter(forum_author=author.id).order_by("-is_created")[:10]
    author_comments = Comment.objects.filter(comment_author=author.id).order_by("-is_created")[:10]
    total_forums = Forum.objects.filter(forum_author=author.id).annotate(num_comments=Count('forum_author'))
    total_comments = Comment.objects.filter(comment_author=author.id).annotate(num_comments=Count('comment_author'))
    template = 'app_author/author_single.html'
    context = {
        'author': author,
        'author_forum_list': author_forum_list,
        'author_comments': author_comments,
        'total_forums': total_forums,
        'total_comments': total_comments
    }
    return render(request, template, context)


@login_required
def author_edit_view(request, slug):
    """
    Render User Edit Form
    :param request:
    :param slug:
    :return:
    """
    author = get_object_or_404(Profile, slug=slug)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=author)
        if form.is_valid():
            author = form.save(commit=False)
            author.save()
            return redirect('author:author_single', slug=slug)
    elif request.user != author.user:
        return redirect('forum:forum_list')
    else:
        form = ProfileForm(instance=author)
    return render(request, 'app_author/author_edit.html', {'author': author, 'form': form})

app_author/templates/app_author/author_edit.html
{% extends "app_forum/main/forum_base.html" %}
{% block title %}Member edit - Django Indonesia{% endblock %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block content %}

    <!-- Include Doodle -->
    {% include "app_forum/partials/_doodle.html" %}
    <!--EOC-->

    <div class="dj-author-edit-wrapper">
        <div class="container-narrow-2">
            <div class="columns">
                <div class="column">
                    <div>
                        <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                            <div class="dj-author-avatar-big-rounded" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ author.profile_picture }}') no-repeat center center;
                                background-size: cover;">
                            </div>
                            <div class="field">
                                <p class="control ">
                                    {{ form.profile_picture|as_crispy_field }}
                                </p>
                            </div>
                            <div class="field">
                                <p class="control has-icons-left">
                                    {{ form.profile_name|as_crispy_field }}
                                </p>
                            </div>
                            <div class="field">
                                <p class="control">
                                    {{ form.profile_location|as_crispy_field }}
                                </p>
                            </div>
                            <div class="field">
                                <p class="control">
                                    {{ form.profile_email|as_crispy_field }}
                                </p>
                            </div>
                            <div class="field">
                                <p class="control">
                                    {{ form.profile_github|as_crispy_field }}
                                </p>
                            </div>
                            <br />
                            <button class="button is-primary" type='submit'>Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app_author/templates/app_author/author_single.html
{% extends "app_forum/main/forum_base.html" %}
{% block title %} Member: {{ author.user }} - Django Indonesia{% endblock %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load show_markdown %}
{% load static %}
{% block content %}

    <div class="dj-author-single-wrapper">

        <!-- AUTHOR BASIC INFO -->
        <div class="dj-author-single-info">
            <div class="container">
                <div class="columns">
                    <div class="column is-narrow">
                         {% if author.profile_picture %}
                        <div class="dj-author-avatar-big-rounded" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ author.profile_picture }}') no-repeat center center; background-size: cover;"></div>
                        {% else %}
                        <div class="dj-author-avatar-big-rounded" style="background: url('{% static "img/you-face.gif" %}') no-repeat center center; background-size: cover;"></div>
                        {% endif %}
                    </div>
                    <div class="column">
                        <div class="dj-author-bio">
                            {% if author.profile_name %}
                            <b>{{ author.profile_name }}</b>
                            {% else %}
                            <b>{{ author.user }}</b>
                            {% endif %}
                            <p><span class="typcn typcn-location-outline"></span>Origin: <strong>{{ author.profile_location }}</strong></p>
                            <p>
                                <a class="button is-dark" href="{{ author.profile_github }}">
                                    <span class="icon is-small">
                                        <span class="typcn typcn-social-github"></span>
                                    </span>
                                </a>
                                <a class="button is-dark" href="mailto:{{ author.profile_email }}">
                                    <span class="icon is-small">
                                        <span class="typcn typcn-mail"></span>
                                    </span>
                                </a>
                            </p>
                        </div>
                    </div>
                    <div class="column">
                        <div class="dj-author-stats">
                            <h5>{{ total_forums.count }}</h5>
                            <p>Threads</p>
                        </div>
                    </div>
                    <div class="column">
                        <div class="dj-author-stats">
                            <h5>{{ total_comments.count }}</h5>
                            <p>Posts</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- EOL -->

        <!-- Include Doodle -->
        {% include "app_forum/partials/_doodle.html" %}
        <!--EOC-->


        <!-- AUTHOR ACTIVITIES -->
        <div class="dj-author-single-activity-wrapper">
            <div class="container">
                <div class="columns">
                    <div class="column">
                        <div class="dj-author-single-widget-wrapper">
                            <div class="dj-author-activity-box">
                                <div class="dj-author-activity-box-meta">
                                    <span class="typcn typcn-pencil"></span> Threads dari <strong>{{ author.user }}</strong>
                                </div>
                                <div class="dj-author-activity-item">
                                    <ul>
                                        {% for author_forum in author_forum_list %}
                                            <li><span class="typcn typcn-arrow-forward"></span> <a href="{% url "forum:forum_single" pk=author_forum.pk %}">{{ author_forum.forum_title }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="dj-author-single-widget-wrapper">
                             <div class="dj-author-activity-box">
                                <div class="dj-author-activity-box-meta">
                                    <span class="typcn typcn-messages"></span> Comments dari <strong>{{ author.user }}</strong>
                                </div>
                                {% for author_forum in author_comments %}
                                <div class="dj-author-activity-item">
                                    <span><a href="{% url "author:author_single" slug=author.slug %}">{{ author_forum.comment_author }}</a> left a reply on <a href="{% url "forum:forum_single" pk=author_forum.forum.id %}">{{ author_forum.forum.forum_title }}</a> {{ author_forum.created_date|naturaltime }}</span>
                                    <p>{{ author_forum.comment_content|show_markdown|safe }}</p>

                                    {{ author_forum.comments }}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- EOL -->

    </div>




{% endblock %}