app_author/urls.py
from django.urls import path

from . import views

app_name = 'app_author'
urlpatterns = [
    path('<slug:slug>/edit', views.author_edit_view, name='author_edit'),
    path('<slug:slug>', views.author_single_view, name='author_single'),
]

app_forum/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'app_forum'
urlpatterns = [
    path('', views.forum_list_view, name='forum_list'),
    path('thread/new/', views.forum_new_view, name='forum_new'),
    path('thread/<int:pk>/', views.forum_single_view, name='forum_single'),
    path('thread/<int:pk>/edit/', views.forum_edit_view, name='forum_edit'),
    path(
        'thread/<int:pk>/comment/edit/<int:id>/',
        views.forum_comment_edit_view,
        name='forum_comment_edit',
    ),
]

admin.site.site_header = 'Django-ID Dashboard'

djangoid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from markdownx import urls as markdownx

urlpatterns = [
    # Main App
    path('', include('app_forum.urls', namespace='forum')),
    path('author/', include('app_author.urls', namespace='author')),
    path('admin/', admin.site.urls),

    # 3rd-party App
    path('markdownx/', include(markdownx)),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_forum/models.py
from django.db import models
from markdownx.models import MarkdownxField

from app_author.models import Profile


class Category(models.Model):
    """
    Category Model
    """
    id = models.AutoField(
        primary_key=True
    )

    category_title = models.CharField(
        max_length=200,
        verbose_name=u'Category Name',
        blank=False,
        null=False
    )

    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return str(self.category_title)

    def save(self, **kwargs):
        if not self.slug:
            from djangoid.utils import get_unique_slug
            self.slug = get_unique_slug(instance=self, field='category_title')
        super(Category, self).save(**kwargs)

    def get_absolute_url(self):
        """
        Call Category Slug
        """
        return 'app_forum:category'


class Forum(models.Model):
    """
    Thread Model
    """

    class Meta:
        verbose_name_plural = "Title"

    forum_author = models.ForeignKey(
        Profile,
        related_name='user_forums',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    forum_title = models.CharField(
        max_length=225,
        verbose_name=u'Title',
        blank=False,
        null=False
    )

    forum_category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        verbose_name=u'Category',
    )

    forum_content = MarkdownxField(
        verbose_name=u'Content (Use Markdown)',
    )

    is_created = models.DateTimeField(
        auto_now_add=True,
        null=True,
        blank=True
    )

    is_modified = models.DateTimeField(
        auto_now=True,
        null=True,
        blank=True
    )

    is_hot = models.BooleanField(
        default=False
    )

    is_closed = models.BooleanField(
        default=False
    )

    def __str__(self):
        return str(self.forum_title)

    def latest_comment_author(self):
        return self.forum_comments.latest('is_created').comment_author

    def latest_comment_date(self):
        return self.forum_comments.latest('is_created').is_created

    def get_absolute_url(self):
        """
        Call Forum ID
        """
        return 'app_forum:forum'


class Comment(models.Model):
    """
    Comment Model
    """

    class Meta:
        verbose_name_plural = "Comment"
        
    forum = models.ForeignKey(
        'Forum',
        on_delete=models.CASCADE,
        related_name='forum_comments'
    )

    comment_author = models.ForeignKey(
        Profile,
        related_name='user_comments',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    comment_content = MarkdownxField(
        verbose_name=u'Markdown',
    )

    is_created = models.DateTimeField(
        auto_now_add=True,
    )

    is_modified = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.comment_content

app_forum/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField

from .models import Forum, Comment


class ThreadForm(forms.ModelForm):
    """
    Comment Form
    """
    class Meta:
        model = Forum
        fields = (
            'forum_title',
            'forum_category',
            'forum_content',
        )
        comment_content = MarkdownxFormField()
        exclude = ['forum_author', 'is_hot']
        widgets = {'forum_author': forms.HiddenInput()}


class CommentForm(forms.ModelForm):
    """
    Comment Form
    """
    class Meta:
        model = Comment
        fields = (
            'comment_content',
        )
        comment_content = MarkdownxFormField()
        exclude = ['comment_author']
        widgets = {'comment_author': forms.HiddenInput()}

app_forum/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from app_author.models import Profile
from .forms import ThreadForm, CommentForm
from .models import Forum, Comment


def forum_list_view(request):
    """
    Render All Threads List
    :param request:
    :return:
    """
    forum_list = Forum.objects.filter(is_hot=False).order_by("-is_modified")
    forum_list_sticky = Forum.objects.filter(is_hot=True).order_by("-is_created")[:1]
    template = 'app_forum/main/forum_list.html'
    paginator = Paginator(forum_list, 10)
    page = request.GET.get('page', 1)
    try:
        forum_list = paginator.page(page)
    except PageNotAnInteger:
        forum_list = paginator.page(1)
    except EmptyPage:
        forum_list = paginator.page(paginator.num_pages)
    context = {'forum_list': forum_list, 'forum_list_sticky': forum_list_sticky}
    return render(request, template, context)


def forum_single_view(request, pk):
    """
    Render Single Thread, Comments and Comment Form
    :param request:
    :param pk:
    :return:
    """
    try:
        forum = Forum.objects.get(pk=pk)
    except Forum.DoesNotExist:
        return redirect('forum:forum_list')
    forum_comments = Comment.objects.filter(forum=forum.id)
    form = CommentForm()
    template = 'app_forum/main/forum_single.html'
    context = {'forum': forum, 'forum_comments': forum_comments, 'form': form}
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_author = Profile.objects.get(user=request.user)
            comment.created_date = datetime.now()
            comment.forum = forum
            comment.save()
            return redirect('forum:forum_single', pk=forum.pk)
    else:
        return render(request, template, context)


@login_required
def forum_new_view(request):
    """
    Render New Thread Form
    :param request:
    :return:
    """
    template = 'app_forum/main/forum_new.html'
    if request.method == "POST":
        form = ThreadForm(request.POST)
        if form.is_valid():
            thread = form.save(commit=False)
            thread.forum_author = Profile.objects.get(user=request.user)
            thread.misc_created = datetime.now()
            thread.save()
            return redirect('forum:forum_list')
    else:
        form = ThreadForm()
    context = {'form': form}
    return render(request, template, context)


@login_required
def forum_edit_view(request, pk):
    """
    Render Edit Form
    :param request:
    :param pk:
    :return:
    """
    try:
        forum = Forum.objects.get(pk=pk)
    except Forum.DoesNotExist:
        return redirect('forum:forum_list')
    template = 'app_forum/main/forum_edit.html'
    if request.method == "POST":
        form = ThreadForm(request.POST, instance=forum)
        if form.is_valid():
            forum = form.save(commit=False)
            forum.forum_author = Profile.objects.get(user=request.user)
            forum.is_created = timezone.now()
            forum.save()
            return redirect('forum:forum_single', pk=forum.pk)
    elif request.user != forum.forum_author.user:
        raise PermissionDenied
    else:
        form = ThreadForm(instance=forum)
    context = {'forum': forum, 'form': form}
    return render(request, template, context)


@login_required
def forum_comment_edit_view(request, pk, id):
    """
    Render Edit Comment Form
    :param request:
    :param pk:
    :param id:
    :return:
    """
    try:
        forum = get_object_or_404(Forum, pk=pk)
        comment = get_object_or_404(Comment, id=id)
    except (Forum.DoesNotExist, Comment.DoesNotExist):
        return redirect('forum:forum_list')
    template = 'app_forum/main/forum_comment_edit.html'
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_author = Profile.objects.get(user=request.user)
            comment.created_date = datetime.now()
            comment.forum = forum
            comment.save()
            return redirect('forum:forum_single', pk=forum.pk)
    elif request.user != comment.comment_author.user:
        raise PermissionDenied
    else:
        form = CommentForm(instance=comment)
    context = {'forum': forum, 'comment': comment, 'form': form}
    return render(request, template, context)

app_forum/templates/app_forum/main/forum_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--Include All Styles-->
        {% include "app_forum/partials/_header.html" %}
        <!--EOC-->

        <title>{% block title %}{% endblock %}</title>
    </head>

    <header>
        <!--Include Navbar-->
        {% include "app_forum/partials/_navbar.html" %}
        <!--EOC-->
    </header>

    <body id="hl-body-wrapper">
        <div id="content" class="site-content">
            {% block content %}
            {% endblock %}
        </div>
    </body>

    <footer class="footer">
        <!--Include Footer-->
        {% include "app_forum/partials/_footer.html" %}
        <!--EOC-->
    </footer>

</html>

app_forum/templates/app_forum/main/forum_comment_edit.html
{% extends "app_forum/main/forum_base.html" %}
{% block title %} Edit Thread - Forum - Django Indonesia{% endblock %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load show_markdown %}
{% load static %}
{% block content %}
{{ form.media }}

    <!-- Include Doodle -->
    {% include "app_forum/partials/_doodle.html" %}
    <!--EOC-->

    {% if request.user.is_authenticated %}
    <div class="dj-forum-form-wrapper">
        <div class="container-narrow">
            <div class="columns">
                <div class="column">
                    <div align="center">
                        <h3><b>~ EDIT COMMENT ~</b></h3>
                    </div>
                </div>
            </div>
            <div class="columns">
                <div class="column is-narrow">
                    {% if request.user.profile.profile_picture %}
                    <div class="dj-author-avatar-rounded" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ request.user.profile.profile_picture }}') no-repeat center center; background-size: cover;">
                    </div>
                    {% else %}
                    <div class="dj-author-avatar-rounded" style="background: url('{% static "img/you-face.gif" %}') no-repeat center center; background-size: cover;">
                    </div>
                    {% endif %}
                </div>
                <div class="column">
                    <div>
                        <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                            <div class="field">
                                <div class="control">
                                    {{ form.comment_content|as_crispy_field|safe }}
                                </div>
                            </div>
                            <br />
                            <button class="button is-primary" type='submit'>Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <h1>Login to reply</h1>
    {% endif %}


{% endblock %}

app_forum/templates/app_forum/main/forum_edit.html
{% extends "app_forum/main/forum_base.html" %}
{% block title %}Edit Thread - Forum - Django Indonesia{% endblock %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load show_markdown %}
{% block content %}
{{ form.media }}

    <!-- Include Doodle -->
    {% include "app_forum/partials/_doodle.html" %}
    <!--EOC-->

    {% if request.user.is_authenticated %}
    <div class="dj-forum-form-wrapper">
        <div class="container-narrow">
            <div class="columns">
                <div class="column">
                    <div align="center">
                        <h3><b>~ EDIT THREAD ~</b></h3>
                    </div>
                </div>
            </div>
            <div class="columns">
                <div class="column is-narrow">
                    <div class="dj-author-avatar-rounded" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ request.user.profile.profile_picture }}') no-repeat center center; background-size: cover;">
                    </div>
                </div>
                <div class="column">
                    <div>
                        <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                            <div class="field">
                                <div class="control">
                                    {{ form.forum_title|as_crispy_field }}
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                    {{ form.forum_category|as_crispy_field }}
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                    {{ form.forum_content|as_crispy_field|safe }}
                                </div>
                            </div>
                            <br />
                            <button class="button is-primary" type='submit'>Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <h1>Login to reply</h1>
    {% endif %}


{% endblock %}

app_forum/templates/app_forum/main/forum_list.html
{% extends "app_forum/main/forum_base.html" %}
{% block title %}Django Indonesia{% endblock %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- HERO -->
    <div class="dj-hero-wrapper">
        <div class="container-narrow-2">
            <div class="columns">
                <div class="column">
                    <div class="dj-hero-content">
                        <h2><b>Selamat datang di komunitas <br/> Django Indonesia</b></h2>
                        <p>
                            <a class="button is-medium is-primary" href="{% url "forum:forum_new" %}">
                                <span class="icon">
                                    <span class="typcn typcn-pencil"></span>
                                </span>
                                <span>Mulai Diskusi</span>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- EOL -->

    <!-- Include Doodle -->
    {% include "app_forum/partials/_doodle.html" %}
    <!--EOC-->

    <!-- Forum List -->
    <div class="dj-forum-list-wrapper">

        <!-- SLACK JOIN -->
        <div align="center">
            <a href="https://django-id.herokuapp.com/">
                <div class="dj-slack-box">
                    <img src="{% static "img/icons8-slack.svg" %}" class="img-valign" />
                    <span class="text2">Join #Slack Django Indonesia!</span>
                </div>
            </a>
        </div>
        <!-- EOL -->

        <!-- STICKY THREAD -->
        <div class="container-narrow-2">
            <div class="columns">
                <div class="column">
                    <div class="dj-forum-list-content">
                        {% for forum in forum_list_sticky %}
                            <a href="{% url "forum:forum_single" pk=forum.pk %}">
                                <div class="dj-forum-list-card card">
                                    <div class="card-body">
                                        <div class="columns">
                                            <div class="column is-narrow">
                                                <div class="dj-forum-list-avatar">
                                                    {% if forum.forum_author.profile_picture %}
                                                    <div class="dj-author-avatar" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ forum.forum_author.profile_picture }}') no-repeat center center; background-size: cover;"></div>
                                                    {% else %}
                                                    <div class="dj-author-avatar" style="background: url('{% static "img/you-face.gif" %}') no-repeat center center; background-size: cover;"></div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="column">
                                                <div class="dj-forum-list-title">
                                                    <h1 class="is-small"><span class="dj-sticky-title">[STICKY]</span> <span class="dj-forum-category-{{ forum.forum_category }}">[{{ forum.forum_category }}]</span> {{ forum.forum_title }} <span class="typcn typcn-flash"></span></h1>
                                                    <p><span class="typcn typcn-arrow-back"></span> <strong>{{ forum.latest_comment_author }}</strong> replied {{ forum.latest_comment_date|naturaltime }}</p>
                                                </div>
                                            </div>
                                            <div class="column is-narrow">
                                                <div class="dj-forum-list-count">
                                                    <p><span class="typcn typcn-messages"></span> {{ forum.forum_comments.count }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- EOL -->

        <!-- ORDINARY THREAD -->
        <div class="container-narrow-2">
            <div class="columns">
                <div class="column">
                    <div class="dj-forum-list-content">
                        {% for forum in forum_list %}
                            <a href="{% url "forum:forum_single" pk=forum.pk %}">
                                <div class="dj-forum-list-card card">
                                    <div class="card-body">
                                        <div class="columns">
                                            <div class="column is-narrow">
                                                <div class="dj-forum-list-avatar">
                                                    {% if forum.forum_author.profile_picture %}
                                                    <div class="dj-author-avatar" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ forum.forum_author.profile_picture }}') no-repeat center center; background-size: cover;"></div>
                                                    {% else %}
                                                    <div class="dj-author-avatar" style="background: url('{% static "img/you-face.gif" %}') no-repeat center center; background-size: cover;"></div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="column">
                                                <div class="dj-forum-list-title">
                                                    <h1 class="is-small"><span class="dj-forum-category-{{ forum.forum_category }}">[{{ forum.forum_category }}]</span> {{ forum.forum_title }}</h1>
                                                    {% if forum.forum_comments.count != 0 %}
                                                    <p><span class="typcn typcn-arrow-back"></span> <strong>{{ forum.latest_comment_author }}</strong> replied {{ forum.latest_comment_date|naturaltime }}</p>
                                                    {% else %}
                                                    <p><span class="typcn typcn-arrow-back"></span> No reply yet...</p>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="column is-narrow">
                                                <div class="dj-forum-list-count">
                                                    <p><span class="typcn typcn-messages"></span> {{ forum.forum_comments.count }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- EOL -->
    </div>
    <!-- EOL -->

    <!-- PAGINATION -->
    <div class="dj-forum-list-pagination-wrapper">
        <div class="container-narrow-2">
            <div class="columns">
                <div class="column">
                    <!--Include Footer-->
                    {% include "app_forum/partials/_pagination.html" %}
                    <!--EOC-->
                </div>
            </div>
        </div>
    </div>
    <!-- EOL -->

{% endblock %}

app_forum/templates/app_forum/main/forum_single.html
{% extends "app_forum/main/forum_base.html" %}
{% block title %} {{ forum.forum_title }} - Forum - Django Indonesia{% endblock %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% load show_markdown %}
{% load static %}
{% block content %}
{{ form.media }}

    <!-- FORUM HEADING, TITLE, AUTHOR -->
    <div class="dj-forum-single-wrapper">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <div class="dj-forum-single-heading">
                        <h1>{{ forum.forum_title }}</h1>
                        <div class="dj-forum-single-author-wrapper">
                             {% if forum.forum_author.profile_picture %}
                            <div class="dj-author-avatar-rounded" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ forum.forum_author.profile_picture }}') no-repeat center center; background-size: cover;"></div>
                            {% else %}
                            <div class="dj-author-avatar-rounded" style="background: url('{% static "img/you-face.gif" %}') no-repeat center center; background-size: cover;"></div>
                            {% endif %}
                        </div>
                        <a href="{% url "author:author_single" slug=forum.forum_author.slug %}" class=""><span class="typcn typcn-user"></span> {{ forum.forum_author }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- EOL -->

    <!-- Include Doodle -->
    {% include "app_forum/partials/_doodle.html" %}
    <!-- EOL -->

    <div class="dj-forum-single-body-wrapper">

        <!-- FORUM CONTENT -->
        <div class="dj-forum-single-content-wrapper">
            <div class="container-narrow">
                <div class="columns">
                    <div class="column">
                        <div class="dj-forum-single-box">
                            <div class="dj-forum-single-box-meta">
                                <ul>
                                    <li><span class="typcn typcn-time"></span> {{ forum.is_created|naturaltime }}</li>
                                    <li><span class="typcn typcn-tag"></span> {{ forum.forum_category }}</li>
                                    <li><span class="typcn typcn-messages"></span> {{ forum.forum_comments.count }}</li>
                                    <li class="float-right">{% if user.is_authenticated and request.user == forum.forum_author.user %}<a href="{% url "forum:forum_edit" pk=forum.pk %}" data-toggle="tooltip" title="Edit Post"><span class="typcn typcn-pencil"></span></a>{% endif %}</li>
                                </ul>
                            </div>
                            <div class="dj-forum-single-content">
                                {{ forum.forum_content|show_markdown|safe }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- EOL -->

        <!-- FORUM COMMENTS -->
        <div class="dj-forum-single-comments-wrapper">
            <div class="container-narrow-2">
                {% for comment in forum_comments %}
                <div class="columns">
                    <div class="column is-narrow" style="text-align: center;">
                        {% if comment.comment_author.profile_picture %}
                        <div class="dj-author-avatar-rounded" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ comment.comment_author.profile_picture }}') no-repeat center center; background-size: cover;"></div>
                        <a href="{% url 'author:author_single' slug=comment.comment_author.slug %}">{{ comment.comment_author }}</a>
                        {% else %}
                        <div class="dj-author-avatar-rounded" style="background: url('{% static "img/you-face.gif" %}') no-repeat center center; background-size: cover;"></div>
                        <a href="{% url 'author:author_single' slug=comment.comment_author.slug %}">{{ comment.comment_author }}</a>
                        {% endif %}
                    </div>
                    <div class="column">
                        <div class="dj-forum-single-box-comment">
                            <div class="dj-forum-single-box-meta-comment">
                                <ul>
                                    <li><span class="typcn typcn-time"></span>created: {{ comment.is_created|naturaltime }}</li>
                                    <li><span class="typcn typcn-edit"></span>modified: {{ comment.is_modified|naturaltime }}</li>
                                    <li class="float-right">{% if user.is_authenticated and request.user == comment.comment_author.user %}<a href="{% url 'forum:forum_comment_edit' pk=forum.pk id=comment.id %}" data-toggle="tooltip" title="Edit Post"><span class="typcn typcn-pencil"></span></a>{% endif %}</li>
                                </ul>
                            </div>
                            <div class="dj-forum-single-content-comment">
                                {{ comment.comment_content|show_markdown|safe }}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- EOL -->

       {% if request.user.is_authenticated and forum.is_closed != True %}
       <div class="dj-forum-single-comment-form-wrapper">
            <div class="container-narrow-3">
                <div class="columns">
                    <div class="column is-narrow">
                        <div class="dj-author-avatar-rounded" style="background: url('{{ request.META.HTTP_NAME }}/media/{{ request.user.profile.profile_picture }}') no-repeat center center; background-size: cover;">
                        </div>
                    </div>
                    <div class="column">
                        <div>
                            <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                                <div class="form-group">
                                    {{ form.comment_content|as_crispy_field|safe }}
                                </div>
                                <button class="button is-primary" type='submit'>Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
       </div>

       {% elif request.user.is_authenticated and forum.misc_closed != False %}

       <div class="dj-forum-closed">
           <h4><span class="typcn typcn-lock-closed" style="color: #f1c40f;"></span> thread closed</h4>
       </div>

        {% elif request.user.is_anonymous %}

        <div class="dj-forum-closed">
            <h4><a href="{% provider_login_url "github" process="login" %}"><span class="typcn typcn-key" style="color: #1abc9c;"></span> login untuk bergabung di diskusi</a></h4>
        </div>

       {% endif %}

        <!--Include Footer-->
        {% include "app_forum/partials/_pagination.html" %}
        <!--EOC-->


    </div>

{% endblock %}