app_author/urls.py
from django.urls import path

from . import views

app_name = 'app_author'
urlpatterns = [
    path('<slug:slug>/edit', views.author_edit_view, name='author_edit'),
    path('<slug:slug>', views.author_single_view, name='author_single'),
]

app_forum/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'app_forum'
urlpatterns = [
    path('', views.forum_list_view, name='forum_list'),
    path('thread/new/', views.forum_new_view, name='forum_new'),
    path('thread/<int:pk>/', views.forum_single_view, name='forum_single'),
    path('thread/<int:pk>/edit/', views.forum_edit_view, name='forum_edit'),
    path(
        'thread/<int:pk>/comment/edit/<int:id>/',
        views.forum_comment_edit_view,
        name='forum_comment_edit',
    ),
]

admin.site.site_header = 'Django-ID Dashboard'

djangoid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from markdownx import urls as markdownx

urlpatterns = [
    # Main App
    path('', include('app_forum.urls', namespace='forum')),
    path('author/', include('app_author.urls', namespace='author')),
    path('admin/', admin.site.urls),

    # 3rd-party App
    path('markdownx/', include(markdownx)),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_forum/models.py
from django.db import models
from markdownx.models import MarkdownxField

from app_author.models import Profile


class Category(models.Model):
    """
    Category Model
    """
    id = models.AutoField(
        primary_key=True
    )

    category_title = models.CharField(
        max_length=200,
        verbose_name=u'Category Name',
        blank=False,
        null=False
    )

    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return str(self.category_title)

    def save(self, **kwargs):
        if not self.slug:
            from djangoid.utils import get_unique_slug
            self.slug = get_unique_slug(instance=self, field='category_title')
        super(Category, self).save(**kwargs)

    def get_absolute_url(self):
        """
        Call Category Slug
        """
        return 'app_forum:category'


class Forum(models.Model):
    """
    Thread Model
    """

    class Meta:
        verbose_name_plural = "Title"

    forum_author = models.ForeignKey(
        Profile,
        related_name='user_forums',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    forum_title = models.CharField(
        max_length=225,
        verbose_name=u'Title',
        blank=False,
        null=False
    )

    forum_category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        verbose_name=u'Category',
    )

    forum_content = MarkdownxField(
        verbose_name=u'Content (Use Markdown)',
    )

    is_created = models.DateTimeField(
        auto_now_add=True,
        null=True,
        blank=True
    )

    is_modified = models.DateTimeField(
        auto_now=True,
        null=True,
        blank=True
    )

    is_hot = models.BooleanField(
        default=False
    )

    is_closed = models.BooleanField(
        default=False
    )

    def __str__(self):
        return str(self.forum_title)

    def latest_comment_author(self):
        return self.forum_comments.latest('is_created').comment_author

    def latest_comment_date(self):
        return self.forum_comments.latest('is_created').is_created

    def get_absolute_url(self):
        """
        Call Forum ID
        """
        return 'app_forum:forum'


class Comment(models.Model):
    """
    Comment Model
    """

    class Meta:
        verbose_name_plural = "Comment"
        
    forum = models.ForeignKey(
        'Forum',
        on_delete=models.CASCADE,
        related_name='forum_comments'
    )

    comment_author = models.ForeignKey(
        Profile,
        related_name='user_comments',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    comment_content = MarkdownxField(
        verbose_name=u'Markdown',
    )

    is_created = models.DateTimeField(
        auto_now_add=True,
    )

    is_modified = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.comment_content

app_forum/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField

from .models import Forum, Comment


class ThreadForm(forms.ModelForm):
    """
    Comment Form
    """
    class Meta:
        model = Forum
        fields = (
            'forum_title',
            'forum_category',
            'forum_content',
        )
        comment_content = MarkdownxFormField()
        exclude = ['forum_author', 'is_hot']
        widgets = {'forum_author': forms.HiddenInput()}


class CommentForm(forms.ModelForm):
    """
    Comment Form
    """
    class Meta:
        model = Comment
        fields = (
            'comment_content',
        )
        comment_content = MarkdownxFormField()
        exclude = ['comment_author']
        widgets = {'comment_author': forms.HiddenInput()}

app_forum/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from app_author.models import Profile
from .forms import ThreadForm, CommentForm
from .models import Forum, Comment


def forum_list_view(request):
    """
    Render All Threads List
    :param request:
    :return:
    """
    forum_list = Forum.objects.filter(is_hot=False).order_by("-is_modified")
    forum_list_sticky = Forum.objects.filter(is_hot=True).order_by("-is_created")[:1]
    template = 'app_forum/main/forum_list.html'
    paginator = Paginator(forum_list, 10)
    page = request.GET.get('page', 1)
    try:
        forum_list = paginator.page(page)
    except PageNotAnInteger:
        forum_list = paginator.page(1)
    except EmptyPage:
        forum_list = paginator.page(paginator.num_pages)
    context = {'forum_list': forum_list, 'forum_list_sticky': forum_list_sticky}
    return render(request, template, context)


def forum_single_view(request, pk):
    """
    Render Single Thread, Comments and Comment Form
    :param request:
    :param pk:
    :return:
    """
    try:
        forum = Forum.objects.get(pk=pk)
    except Forum.DoesNotExist:
        return redirect('forum:forum_list')
    forum_comments = Comment.objects.filter(forum=forum.id)
    form = CommentForm()
    template = 'app_forum/main/forum_single.html'
    context = {'forum': forum, 'forum_comments': forum_comments, 'form': form}
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_author = Profile.objects.get(user=request.user)
            comment.created_date = datetime.now()
            comment.forum = forum
            comment.save()
            return redirect('forum:forum_single', pk=forum.pk)
    else:
        return render(request, template, context)


@login_required
def forum_new_view(request):
    """
    Render New Thread Form
    :param request:
    :return:
    """
    template = 'app_forum/main/forum_new.html'
    if request.method == "POST":
        form = ThreadForm(request.POST)
        if form.is_valid():
            thread = form.save(commit=False)
            thread.forum_author = Profile.objects.get(user=request.user)
            thread.misc_created = datetime.now()
            thread.save()
            return redirect('forum:forum_list')
    else:
        form = ThreadForm()
    context = {'form': form}
    return render(request, template, context)


@login_required
def forum_edit_view(request, pk):
    """
    Render Edit Form
    :param request:
    :param pk:
    :return:
    """
    try:
        forum = Forum.objects.get(pk=pk)
    except Forum.DoesNotExist:
        return redirect('forum:forum_list')
    template = 'app_forum/main/forum_edit.html'
    if request.method == "POST":
        form = ThreadForm(request.POST, instance=forum)
        if form.is_valid():
            forum = form.save(commit=False)
            forum.forum_author = Profile.objects.get(user=request.user)
            forum.is_created = timezone.now()
            forum.save()
            return redirect('forum:forum_single', pk=forum.pk)
    elif request.user != forum.forum_author.user:
        raise PermissionDenied
    else:
        form = ThreadForm(instance=forum)
    context = {'forum': forum, 'form': form}
    return render(request, template, context)


@login_required
def forum_comment_edit_view(request, pk, id):
    """
    Render Edit Comment Form
    :param request:
    :param pk:
    :param id:
    :return:
    """
    try:
        forum = get_object_or_404(Forum, pk=pk)
        comment = get_object_or_404(Comment, id=id)
    except (Forum.DoesNotExist, Comment.DoesNotExist):
        return redirect('forum:forum_list')
    template = 'app_forum/main/forum_comment_edit.html'
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_author = Profile.objects.get(user=request.user)
            comment.created_date = datetime.now()
            comment.forum = forum
            comment.save()
            return redirect('forum:forum_single', pk=forum.pk)
    elif request.user != comment.comment_author.user:
        raise PermissionDenied
    else:
        form = CommentForm(instance=comment)
    context = {'forum': forum, 'comment': comment, 'form': form}
    return render(request, template, context)

app_forum/templates/app_forum/partials/_footer.html
{% load static %}
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered dj-footer-wrapper">
      <p>
        <strong>&copy; 2017 Django Indonesia</strong>
      </p>
      <p>
        <ul>
            <li><a href="https://www.facebook.com/groups/DjangoID/"><img src="{% static "img/icons8-facebook_filled.svg" %}"></a></li>
            <li><a href="https://github.com/django-id/"><img src="{% static "img/icons8-github_filled.svg" %}"></a></li>
            <li><a href="https://django-id.herokuapp.com/"><img src="{% static "img/icons8-slack_filled.svg" %}"></a></li>
        </ul>
      </p>
    </div>
  </div>
</footer>

app_forum/templates/app_forum/partials/_header.html
{% load static %}
<!-- SEO -->
<meta charset="UTF-8">
<meta name="description" content="Komunitas Django Framework Indonesia. Tempat sharing dan diskusi seputar web development menggunakan Django Web Framework">
<meta name="keywords" content="django, django framework, django indonesia, python, komunitas django indonesia, django-id">
<meta name="author" content="Alzea Arafat">
<!--EOC-->

<!-- INCLUDE ALL STYLES -->
<link rel="stylesheet" type="text/css" href="{% static "css/bulma.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/typicons.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/pygments.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/base.min.css" %}">
<!-- EOC -->

<!-- FAVICON -->
<link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
<link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
<!-- EOL -->

<!-- TELL BROWSER, THIS SITE IS MOBILE READY -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- EOC -->

app_forum/templates/app_forum/partials/_navbar.html
{% load account %}
{% load socialaccount %}
{% load staticfiles %}
<div class="dj-navbar-wrapper">
    <div class="container">
        <nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="{% static 'img/Logo.png' %}" alt="Django Indonesia" width="112" height="28">
                </a>

                <button class="button navbar-burger">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>

            <div class="navbar-menu">
                <div class="navbar-end">
                    <a class="navbar-item">
                        {% if not request.user.is_authenticated %}
                        <p class="control">
                            <a class="button" href="{% provider_login_url "github" process="login" %}">
                                <span class="icon">
                                    <span class="typcn typcn-social-github"></span>
                                </span>
                                <span>Login with Github</span>
                            </a>
                        </p>
                        {% else %}
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link">
                                Halo, {{ request.user.username }}
                            </a>
                            <div class="navbar-dropdown is-boxed">
                                 <a class="navbar-item" href="{% url 'author:author_single' slug=request.user.username %}">
                                    Lihat Profile
                                </a>
                                <a class="navbar-item" href="{% url 'author:author_edit' slug=request.user.username %}">
                                    Edit Profile
                                </a>
                                <a class="navbar-item" href="{% url "forum:forum_new" %}">
                                    Buat Thread Baru
                                </a>
                                <hr class="navbar-divider">
                                <div class="navbar-item">
                                    Logout
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </a>
                </div>
            </div>
        </nav>
    </div>
</div>